/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasibookingtiketfix;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author ASUS
 */
public class DetailTheBox extends javax.swing.JFrame {
    String film, hari,tanggal, jam,harga, hrg;
    public static javax.swing.JTextField tf_jam;
    public static javax.swing.JTextField tf_harga;
    

    /**
     * Creates new form DetailTheBox
     */
    public DetailTheBox() {
        initComponents();
        // center form 
        this.setLocationRelativeTo(null);
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        minimize.setBorder(label_border);
        close.setBorder(label_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        judul6 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        senin = new javax.swing.JButton();
        selasa = new javax.swing.JButton();
        kamis = new javax.swing.JButton();
        rabu = new javax.swing.JButton();
        jumat = new javax.swing.JButton();
        sabtu = new javax.swing.JButton();
        minggu = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 42)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("THE BOX");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasibookingtiketfix/tb.jpg"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Directors: Yang Jeong-woong\nStars    : Park Chanyeol, Dal-Hwan Jo\nDuration : 46 minutes\nRating   : R (Remaja)\nGenre    : Musical/Music\n\nMengisahkan tentang penyanyi dengan \nsemangat tinggi dalam musik yang \nbernama Ji Hoon. Memiliki parasa yang \ntampan serta jago bernyanyi, Ji Hoon \nselalu mempersengarkan suara emasnya \nsetiap hari di jalanan sebagai pengamen. Tidak ingin \nmimpinya terhenti, ia pun tetap \nharus bernyanyi tanpa kenal tempat.\nHidup Ji Hoon mulai berubah ketika \nia bertemu dengan Min Soo, seorang \nproduser musik yang dulunya sukses \nbesar di industri ini. Bersama-sama, \nmereka memulai perjalanan musik yang \nmendebarkan.\n\nKeduanya akhirnya secara bersama-sama \nmemulai perjalanan mereka untuk \nmenjadi seorang musisi dan produser\nmusik yang sukses.");
        jScrollPane1.setViewportView(jTextArea1);

        judul6.setBackground(new java.awt.Color(153, 153, 153));

        jLabel36.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jLabel36.setText("SENIN-KAMIS               JUMAT           SABTU-MINGGU");

        jLabel37.setBackground(new java.awt.Color(0, 255, 102));
        jLabel37.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jLabel37.setText("       40.000                          50.000                         65.000");

        javax.swing.GroupLayout judul6Layout = new javax.swing.GroupLayout(judul6);
        judul6.setLayout(judul6Layout);
        judul6Layout.setHorizontalGroup(
            judul6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judul6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(judul6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(judul6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel36))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        judul6Layout.setVerticalGroup(
            judul6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judul6Layout.createSequentialGroup()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        senin.setText("Senin, 2021-06-21 15:00");
        senin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        senin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seninActionPerformed(evt);
            }
        });

        selasa.setText("Selasa, 2021-06-22 15:00");
        selasa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selasaActionPerformed(evt);
            }
        });

        kamis.setText("Kamis, 2021-06-24 15:00");
        kamis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kamis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kamisActionPerformed(evt);
            }
        });

        rabu.setText("Rabu, 2021-06-23 15:00");
        rabu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rabu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabuActionPerformed(evt);
            }
        });

        jumat.setText("Jumat, 2021-06-25 15:00");
        jumat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jumat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumatActionPerformed(evt);
            }
        });

        sabtu.setText("Sabtu, 2021-06-26 15:00");
        sabtu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sabtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabtuActionPerformed(evt);
            }
        });

        minggu.setText("Minggu, 2021-06-27 15:00");
        minggu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minggu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mingguActionPerformed(evt);
            }
        });

        close.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText(" X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        minimize.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setText(" -");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(senin, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(selasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(judul6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rabu, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kamis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jumat, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sabtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(minggu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(close)
                            .addComponent(minimize))))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(judul6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selasa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rabu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kamis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sabtu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(minggu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void seninActionPerformed(java.awt.event.ActionEvent evt) {                                      
        KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Senin";
        tanggal="2021-06-21";
        jam="15:00";
        hrg="40000";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
        KursiStudioTB.tf_hargapokok.setText(hrg);
    }                                     

    private void selasaActionPerformed(java.awt.event.ActionEvent evt) {                                       
         KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Selasa";
        tanggal="2021-06-22";
        jam="15:00";
        hrg="40000";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
        KursiStudioTB.tf_hargapokok.setText(hrg);
    }                                      

    private void kamisActionPerformed(java.awt.event.ActionEvent evt) {                                      
        KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Rabu";
        tanggal="2021-06-24";
        jam="15:00";
        hrg="40000";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
        KursiStudioTB.tf_hargapokok.setText(hrg);
    }                                     

    private void rabuActionPerformed(java.awt.event.ActionEvent evt) {                                     
         KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Kamis";
        tanggal="2021-06-23";
        jam="15:00";
        hrg="40000";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
        KursiStudioTB.tf_hargapokok.setText(hrg);
    }                                    

    private void jumatActionPerformed(java.awt.event.ActionEvent evt) {                                      
         KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Jumat";
        tanggal="2021-06-25";
        jam="15:00";
        hrg="50000";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
        KursiStudioTB.tf_hargapokok.setText(hrg);
    }                                     

    private void sabtuActionPerformed(java.awt.event.ActionEvent evt) {                                      
         KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Sabtu";
        tanggal="2021-06-26";
        jam="15:00";
        hrg="65000";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
        KursiStudioTB.tf_hargapokok.setText(hrg);
    }                                     

    private void mingguActionPerformed(java.awt.event.ActionEvent evt) {                                       
         KursiStudioTB thebox = new KursiStudioTB();
        thebox.setVisible(true);
        thebox.pack();
        thebox.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

        film="The Box";
        hari="Minggu";
        tanggal="2021-06-27";
        jam="15:00";
        hrg="65000";

        KursiStudioTB.tf_namafilm.setText(film);
        KursiStudioTB.tf_hari.setText(hari);
        KursiStudioTB.tf_tanggal.setText(tanggal);
        KursiStudioTB.tf_jam.setText(jam);
        KursiStudioTB.tf_hargapokok.setText(hrg);
    }                                      

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {                                   
        System.exit(0);
    }                                  

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {                                   
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        close.setBorder(judul_border);
        close.setForeground(Color.red);
    }                                  

    private void closeMouseExited(java.awt.event.MouseEvent evt) {                                  
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        close.setBorder(judul_border);
        close.setForeground(Color.white);
    }                                 

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {                                      
        this.setState(JFrame.ICONIFIED);
    }                                     

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {                                      
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        minimize.setBorder(judul_border);
        minimize.setForeground(Color.red);
    }                                     

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {                                     
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        minimize.setBorder(judul_border);
        minimize.setForeground(Color.white);
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailTheBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailTheBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailTheBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailTheBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailTheBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel judul6;
    private javax.swing.JButton jumat;
    private javax.swing.JButton kamis;
    private javax.swing.JButton minggu;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton rabu;
    private javax.swing.JButton sabtu;
    private javax.swing.JButton selasa;
    private javax.swing.JButton senin;
    // End of variables declaration                   
}
