/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasibookingtiket;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class KursiStudioGK extends javax.swing.JFrame {
     
     public String film;
     public int pil;
     public javax.swing.JButton buttongodzilla;
     public javax.swing.JButton buttonthebox;
     public javax.swing.JButton buttonnerve;
     public String kursi;
     int harga, hasil, jumlah, uang, kembali;
     int jmlkursi;
     String jam, hari;
     int counter = 0;
     
    /**
     * Creates new form KursiStudioGK
     */
    public KursiStudioGK() {
        initComponents();
        
        // center form 
        this.setLocationRelativeTo(null);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonnext = new javax.swing.JButton();
        buttonback = new javax.swing.JButton();
        checkbox_b6 = new javax.swing.JCheckBox();
        checkbox_b5 = new javax.swing.JCheckBox();
        checkbox_b4 = new javax.swing.JCheckBox();
        checkbox_b2 = new javax.swing.JCheckBox();
        checkbox_b3 = new javax.swing.JCheckBox();
        checkbox_b1 = new javax.swing.JCheckBox();
        checkbox_a6 = new javax.swing.JCheckBox();
        checkbox_a5 = new javax.swing.JCheckBox();
        checkbox_a3 = new javax.swing.JCheckBox();
        checkbox_a4 = new javax.swing.JCheckBox();
        checkbox_a2 = new javax.swing.JCheckBox();
        checkbox_a1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_namafilm = new javax.swing.JTextField();
        cb_hari = new javax.swing.JComboBox<>();
        tf_nokursi = new javax.swing.JTextField();
        tf_jam = new javax.swing.JTextField();
        tf_harga = new javax.swing.JTextField();
        tf_uangbyr = new javax.swing.JTextField();
        tf_uangkembali = new javax.swing.JTextField();
        buttonreset = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_jmltiket = new javax.swing.JTextField();
        judul5 = new javax.swing.JPanel();
        konfirmasi = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STUDIO ");

        buttonnext.setBackground(new java.awt.Color(255, 255, 255));
        buttonnext.setText("BOOK");
        buttonnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonnextActionPerformed(evt);
            }
        });

        buttonback.setBackground(new java.awt.Color(255, 255, 255));
        buttonback.setText("BACK");
        buttonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbackActionPerformed(evt);
            }
        });

        checkbox_b6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_b6.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_b6.setText("B6");
        checkbox_b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_b6ActionPerformed(evt);
            }
        });

        checkbox_b5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_b5.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_b5.setText("B5");
        checkbox_b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_b5ActionPerformed(evt);
            }
        });

        checkbox_b4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_b4.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_b4.setText(" B4");
        checkbox_b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_b4ActionPerformed(evt);
            }
        });

        checkbox_b2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_b2.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_b2.setText(" B2");
        checkbox_b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_b2ActionPerformed(evt);
            }
        });

        checkbox_b3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_b3.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_b3.setText(" B3");
        checkbox_b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_b3ActionPerformed(evt);
            }
        });

        checkbox_b1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_b1.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_b1.setText(" B1");
        checkbox_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_b1ActionPerformed(evt);
            }
        });

        checkbox_a6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_a6.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_a6.setText(" A6");
        checkbox_a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_a6ActionPerformed(evt);
            }
        });

        checkbox_a5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_a5.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_a5.setText(" A5");
        checkbox_a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_a5ActionPerformed(evt);
            }
        });

        checkbox_a3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_a3.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_a3.setText(" A3");
        checkbox_a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_a3ActionPerformed(evt);
            }
        });

        checkbox_a4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_a4.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_a4.setText(" A4");
        checkbox_a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_a4ActionPerformed(evt);
            }
        });

        checkbox_a2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_a2.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_a2.setText(" A2");
        checkbox_a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_a2ActionPerformed(evt);
            }
        });

        checkbox_a1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_a1.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_a1.setText(" A1");
        checkbox_a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_a1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Nama Film");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Hari");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Jam");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Nomor Kursi");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("Jumlah Tiket");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Harga");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setText("Uang Bayar");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setText("Uang Kembali");

        tf_namafilm.setEditable(false);
        tf_namafilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_namafilmActionPerformed(evt);
            }
        });

        cb_hari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));
        cb_hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_hariActionPerformed(evt);
            }
        });

        tf_nokursi.setEditable(false);

        tf_jam.setEditable(false);
        tf_jam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_jamActionPerformed(evt);
            }
        });
        tf_jam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_jamKeyReleased(evt);
            }
        });

        tf_harga.setEditable(false);
        tf_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hargaActionPerformed(evt);
            }
        });

        tf_uangbyr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_uangbyrActionPerformed(evt);
            }
        });
        tf_uangbyr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_uangbyrKeyReleased(evt);
            }
        });

        tf_uangkembali.setEditable(false);

        buttonreset.setBackground(new java.awt.Color(255, 255, 255));
        buttonreset.setText("RESET");
        buttonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonresetActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel10.setText("LAYAR BIOSKOP");

        tf_jmltiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_jmltiketActionPerformed(evt);
            }
        });
        tf_jmltiket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_jmltiketKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tf_jmltiket);

        judul5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel32.setText("       Senin - Kamis     : 40.000");

        jLabel33.setText("       Jumat                   : 50.000");

        jLabel34.setText("       Sabtu & Minggu  : 65.000");

        javax.swing.GroupLayout judul5Layout = new javax.swing.GroupLayout(judul5);
        judul5.setLayout(judul5Layout);
        judul5Layout.setHorizontalGroup(
            judul5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judul5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(judul5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, judul5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel33))
                    .addGroup(judul5Layout.createSequentialGroup()
                        .addGroup(judul5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        judul5Layout.setVerticalGroup(
            judul5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judul5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(judul5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nokursi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tf_harga, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_jam, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_namafilm, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cb_hari, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tf_uangbyr, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_uangkembali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonback, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonreset, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(checkbox_b1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkbox_b2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkbox_b3)
                                        .addGap(96, 96, 96)
                                        .addComponent(checkbox_b4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkbox_b5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkbox_b6)
                                        .addGap(59, 59, 59))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(checkbox_a1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkbox_a2)
                                        .addGap(106, 106, 106)
                                        .addComponent(checkbox_a3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkbox_a4)
                                        .addGap(94, 94, 94)
                                        .addComponent(checkbox_a5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkbox_a6)))
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonnext, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(240, 240, 240))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(358, 358, 358))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkbox_a6)
                    .addComponent(checkbox_a4)
                    .addComponent(checkbox_a3)
                    .addComponent(checkbox_a2)
                    .addComponent(checkbox_a1)
                    .addComponent(checkbox_a5))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkbox_b1)
                    .addComponent(checkbox_b2)
                    .addComponent(checkbox_b3)
                    .addComponent(checkbox_b4)
                    .addComponent(checkbox_b5)
                    .addComponent(checkbox_b6))
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonnext, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonreset, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonback, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(judul5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_namafilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nokursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tf_jam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tf_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_uangbyr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_uangkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(144, 144, 144))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonnextActionPerformed

        String namafilm = tf_namafilm.getText();
        String hari = String.valueOf(cb_hari.getSelectedItem());
        String jamtayang= tf_jam.getText();
        String nokursi = tf_nokursi.getText();
        String jumlahtiket = tf_jmltiket.getText();
        String harga_total = tf_harga.getText();
      
        
        if(validasikolom())
        {
            if(!validasikursi(nokursi))
            {
                PreparedStatement ps;
                ResultSet rs;
                String kursi_user_query = "INSERT INTO tb_booking_gk (nama_film, hari, jam, nomor_kursi, jumlah_tiket, total_harga) VALUES (?,?,?,?,?,?)" ;
                
                
                try {
                    // memanggil class javatomysql
                    ps = javatomysql.getConnection().prepareStatement(kursi_user_query);
                    // mengambil inputan
                    ps.setString(1, namafilm);
                    ps.setString(2, hari);
                    ps.setString(3, jamtayang);
                    ps.setString(4, nokursi);
                    ps.setString(5, jumlahtiket);
                    ps.setString(6, harga_total);

                    if(ps.executeUpdate()!=0){
                        // pesan sukses
                        JOptionPane.showMessageDialog(null, "Your Ticket Successfully Booked!");
                    }
                    else{
                        // pesan error
                        JOptionPane.showMessageDialog(null, "Error : Check Your Information");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(KursiStudioGK.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }//GEN-LAST:event_buttonnextActionPerformed

    private void buttonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbackActionPerformed
        MoviesForm mf = new MoviesForm();
        mf.setVisible(true);
        mf.pack();
        mf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_buttonbackActionPerformed

    private void checkbox_a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_a1ActionPerformed
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_a1.getText();
        tf_nokursi.setText(kursi);
        checkbox_a1.setEnabled(false);
    }//GEN-LAST:event_checkbox_a1ActionPerformed

    private void checkbox_a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_a2ActionPerformed
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_a2.getText();
        tf_nokursi.setText(kursi);
        checkbox_a2.setEnabled(false);
    }//GEN-LAST:event_checkbox_a2ActionPerformed

    private void buttonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonresetActionPerformed
        tf_jmltiket.setText("");
        tf_harga.setText("");
        tf_uangbyr.setText("");
        tf_uangkembali.setText("");
        tf_nokursi.setText("");
        cb_hari.setSelectedIndex(0);
        counter= 0;
         
        checkbox_a1.setEnabled(true); 
        checkbox_a2.setEnabled(true);
        checkbox_a3.setEnabled(true);
        checkbox_a4.setEnabled(true);
        checkbox_a5.setEnabled(true);
        checkbox_a6.setEnabled(true);
        checkbox_b1.setEnabled(true);
        checkbox_b2.setEnabled(true);
        checkbox_b3.setEnabled(true);
        checkbox_b4.setEnabled(true);
        checkbox_b5.setEnabled(true);
        checkbox_b6.setEnabled(true);
        checkbox_a1.setSelected(false); 
        checkbox_a2.setSelected(false);
        checkbox_a3.setSelected(false);
        checkbox_a4.setSelected(false);
        checkbox_a5.setSelected(false);
        checkbox_a6.setSelected(false);
        checkbox_b1.setSelected(false);
        checkbox_b2.setSelected(false);
        checkbox_b3.setSelected(false);
        checkbox_b4.setSelected(false);
        checkbox_b5.setSelected(false);
        checkbox_b6.setSelected(false);
    }//GEN-LAST:event_buttonresetActionPerformed

    private void checkbox_b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_b1ActionPerformed
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_b1.getText();
        tf_nokursi.setText(kursi);
        checkbox_b1.setEnabled(false);
    }//GEN-LAST:event_checkbox_b1ActionPerformed

    private void checkbox_a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_a3ActionPerformed
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_a3.getText();
        tf_nokursi.setText(kursi);
        checkbox_a3.setEnabled(false);
    }//GEN-LAST:event_checkbox_a3ActionPerformed

    private void checkbox_a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_a4ActionPerformed
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_a4.getText();
        tf_nokursi.setText(kursi);
        checkbox_a4.setEnabled(false);
    }//GEN-LAST:event_checkbox_a4ActionPerformed

    private void checkbox_a5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_a5ActionPerformed
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_a5.getText();
        tf_nokursi.setText(kursi);
        checkbox_a5.setEnabled(false);
    }//GEN-LAST:event_checkbox_a5ActionPerformed

    private void checkbox_a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_a6ActionPerformed
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_a6.getText();
        tf_nokursi.setText(kursi);
        checkbox_a6.setEnabled(false);
    }//GEN-LAST:event_checkbox_a6ActionPerformed

    private void checkbox_b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_b2ActionPerformed
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_b2.getText();
        tf_nokursi.setText(kursi);
        checkbox_b2.setEnabled(false);
    }//GEN-LAST:event_checkbox_b2ActionPerformed

    private void checkbox_b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_b3ActionPerformed
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_b3.getText();
        tf_nokursi.setText(kursi);
        checkbox_b3.setEnabled(false);
    }//GEN-LAST:event_checkbox_b3ActionPerformed

    private void checkbox_b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_b4ActionPerformed
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_b4.getText();
        tf_nokursi.setText(kursi);
        checkbox_b4.setEnabled(false);
    }//GEN-LAST:event_checkbox_b4ActionPerformed

    private void checkbox_b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_b5ActionPerformed
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_b5.getText();
        tf_nokursi.setText(kursi);
        checkbox_b5.setEnabled(false);
    }//GEN-LAST:event_checkbox_b5ActionPerformed

    private void checkbox_b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_b6ActionPerformed
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_b6.getText();
        tf_nokursi.setText(kursi);
        checkbox_b6.setEnabled(false);
    }//GEN-LAST:event_checkbox_b6ActionPerformed

    private void tf_namafilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_namafilmActionPerformed
    
    }//GEN-LAST:event_tf_namafilmActionPerformed

    private void cb_hariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_hariActionPerformed
        if(cb_hari.getSelectedItem().equals("Senin")){
            harga = 40000;
        }else if(cb_hari.getSelectedItem().equals("Selasa")){
            harga = 40000;
        }else if(cb_hari.getSelectedItem().equals("Rabu")){
            harga = 40000;
        }else if(cb_hari.getSelectedItem().equals("Kamis")){
            harga = 40000;
        }else if(cb_hari.getSelectedItem().equals("Jumat")){
            harga = 50000;
        }else if(cb_hari.getSelectedItem().equals("Sabtu")){
            harga = 65000;
        }else if(cb_hari.getSelectedItem().equals("Minggu")){
            harga = 65000;
        }
    }//GEN-LAST:event_cb_hariActionPerformed
     
    private void konfirmasiActionPerformed(java.awt.event.ActionEvent evt) {                                           

        hasil = counter * harga;
        tf_harga.setText(String.valueOf(hasil));
        tf_jmltiket.setText(String.valueOf(counter));
    } 

    private void tf_jmltiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_jmltiketActionPerformed
       
    }//GEN-LAST:event_tf_jmltiketActionPerformed

    private void tf_uangbyrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_uangbyrActionPerformed
  
    }//GEN-LAST:event_tf_uangbyrActionPerformed

    private void tf_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hargaActionPerformed
     
    }//GEN-LAST:event_tf_hargaActionPerformed

    private void tf_uangbyrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_uangbyrKeyReleased
        uang =Integer.parseInt(String.valueOf(tf_uangbyr.getText()));
        kembali = uang - hasil;
        tf_uangkembali.setText(String.valueOf(kembali));
    }//GEN-LAST:event_tf_uangbyrKeyReleased

    private void tf_jamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_jamActionPerformed
       
    }//GEN-LAST:event_tf_jamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KursiStudioGK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KursiStudioGK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KursiStudioGK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KursiStudioGK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KursiStudioGK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonback;
    private javax.swing.JButton buttonnext;
    private javax.swing.JButton buttonreset;
    private javax.swing.JComboBox<String> cb_hari;
    private javax.swing.JCheckBox checkbox_a1;
    private javax.swing.JCheckBox checkbox_a2;
    private javax.swing.JCheckBox checkbox_a3;
    private javax.swing.JCheckBox checkbox_a4;
    private javax.swing.JCheckBox checkbox_a5;
    private javax.swing.JCheckBox checkbox_a6;
    private javax.swing.JCheckBox checkbox_b1;
    private javax.swing.JCheckBox checkbox_b2;
    private javax.swing.JCheckBox checkbox_b3;
    private javax.swing.JCheckBox checkbox_b4;
    private javax.swing.JCheckBox checkbox_b5;
    private javax.swing.JCheckBox checkbox_b6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel judul;
    private javax.swing.JPanel judul1;
    private javax.swing.JPanel judul2;
    private javax.swing.JPanel judul3;
    private javax.swing.JPanel judul4;
    private javax.swing.JPanel judul5;
    private javax.swing.JButton konfirmasi;
    private javax.swing.JTextField tf_harga;
    public static javax.swing.JTextField tf_jam;
    private javax.swing.JTextField tf_jmltiket;
    public static javax.swing.JTextField tf_namafilm;
    private javax.swing.JTextField tf_nokursi;
    private javax.swing.JTextField tf_uangbyr;
    private javax.swing.JTextField tf_uangkembali;
    // End of variables declaration//GEN-END:variables
}
