/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasibookingtiketfix;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author ASUS
 */
public class KursiStudioTB extends javax.swing.JFrame {
     public String film;
     public int pil;
     public javax.swing.JButton buttongodzilla;
     public javax.swing.JButton buttonthebox;
     public javax.swing.JButton buttonnerve;
     public String kursi;
     int hasil, jumlah, uang, kembali, hargahari, harga;
     int jmlkursi;
     String jam, hari, hargaa;
     int counter = 0;

    /**
     * Creates new form KursiStudioTB
     */
    public KursiStudioTB() {
        initComponents();
        // center form 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_hargapokok = new javax.swing.JTextField();
        tf_hari = new javax.swing.JTextField();
        tf_tanggal = new javax.swing.JTextField();
        tf_nokursi = new javax.swing.JTextField();
        tf_jam = new javax.swing.JTextField();
        tf_jmltiket = new javax.swing.JTextField();
        tf_totalharga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        checkbox_a1 = new javax.swing.JCheckBox();
        checkbox_a2 = new javax.swing.JCheckBox();
        checkbox_b1 = new javax.swing.JCheckBox();
        checkbox_b2 = new javax.swing.JCheckBox();
        checkbox_b3 = new javax.swing.JCheckBox();
        checkbox_a3 = new javax.swing.JCheckBox();
        checkbox_a4 = new javax.swing.JCheckBox();
        checkbox_a5 = new javax.swing.JCheckBox();
        checkbox_b4 = new javax.swing.JCheckBox();
        checkbox_b5 = new javax.swing.JCheckBox();
        checkbox_b6 = new javax.swing.JCheckBox();
        checkbox_a6 = new javax.swing.JCheckBox();
        konfirmasi = new javax.swing.JButton();
        buttonback = new javax.swing.JButton();
        buttonreset = new javax.swing.JButton();
        buttonbook = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        tf_uangbyr = new javax.swing.JTextField();
        tf_uangkembali = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_namafilm = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("STUDIO");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(480, 50, 180, 60);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Film              :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 210, 180, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hari                       :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 250, 175, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal                  :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 290, 180, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jumlah Tiket           :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 410, 184, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jam                       :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(70, 370, 180, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nomor Kursi            :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(70, 330, 190, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Harga            :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(70, 490, 178, 22);

        tf_hargapokok.setEditable(false);
        jPanel2.add(tf_hargapokok);
        tf_hargapokok.setBounds(270, 450, 150, 26);

        tf_hari.setEditable(false);
        jPanel2.add(tf_hari);
        tf_hari.setBounds(270, 250, 150, 26);

        tf_tanggal.setEditable(false);
        jPanel2.add(tf_tanggal);
        tf_tanggal.setBounds(270, 290, 150, 26);

        tf_nokursi.setEditable(false);
        jPanel2.add(tf_nokursi);
        tf_nokursi.setBounds(270, 330, 150, 26);

        tf_jam.setEditable(false);
        jPanel2.add(tf_jam);
        tf_jam.setBounds(270, 370, 150, 26);

        tf_jmltiket.setEditable(false);
        jPanel2.add(tf_jmltiket);
        tf_jmltiket.setBounds(270, 410, 150, 26);

        tf_totalharga.setEditable(false);
        jPanel2.add(tf_totalharga);
        tf_totalharga.setBounds(270, 490, 152, 26);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("LAYAR BIOSKOP");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(750, 250, 133, 22);

        checkbox_a1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_a1.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_a1.setText(" A1");
        checkbox_a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_a1ActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox_a1);
        checkbox_a1.setBounds(531, 340, 59, 31);

        checkbox_a2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_a2.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_a2.setText(" A2");
        checkbox_a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_a2ActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox_a2);
        checkbox_a2.setBounds(597, 340, 59, 31);

        checkbox_b1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_b1.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_b1.setText(" B1");
        checkbox_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_b1ActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox_b1);
        checkbox_b1.setBounds(597, 400, 59, 31);

        checkbox_b2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_b2.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_b2.setText(" B2");
        checkbox_b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_b2ActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox_b2);
        checkbox_b2.setBounds(663, 400, 59, 31);

        checkbox_b3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_b3.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_b3.setText(" B3");
        checkbox_b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_b3ActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox_b3);
        checkbox_b3.setBounds(727, 400, 59, 31);

        checkbox_a3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_a3.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_a3.setText(" A3");
        checkbox_a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_a3ActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox_a3);
        checkbox_a3.setBounds(757, 340, 59, 31);

        checkbox_a4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_a4.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_a4.setText(" A4");
        checkbox_a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_a4ActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox_a4);
        checkbox_a4.setBounds(817, 340, 59, 31);

        checkbox_a5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_a5.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_a5.setText(" A5");
        checkbox_a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_a5ActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox_a5);
        checkbox_a5.setBounds(972, 340, 59, 31);

        checkbox_b4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_b4.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_b4.setText(" B4");
        checkbox_b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_b4ActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox_b4);
        checkbox_b4.setBounds(846, 400, 59, 31);

        checkbox_b5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_b5.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_b5.setText(" B5");
        checkbox_b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_b5ActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox_b5);
        checkbox_b5.setBounds(906, 400, 59, 31);

        checkbox_b6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_b6.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_b6.setText(" B6");
        checkbox_b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_b6ActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox_b6);
        checkbox_b6.setBounds(972, 400, 59, 31);

        checkbox_a6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        checkbox_a6.setForeground(new java.awt.Color(255, 255, 255));
        checkbox_a6.setText(" A6");
        checkbox_a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_a6ActionPerformed(evt);
            }
        });
        jPanel2.add(checkbox_a6);
        checkbox_a6.setBounds(1032, 340, 59, 31);

        konfirmasi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        konfirmasi.setText("KONFIRMASI KURSI");
        konfirmasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasiActionPerformed(evt);
            }
        });
        jPanel2.add(konfirmasi);
        konfirmasi.setBounds(721, 486, 195, 31);

        buttonback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonback.setText("BACK");
        buttonback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbackActionPerformed(evt);
            }
        });
        jPanel2.add(buttonback);
        buttonback.setBounds(15, 642, 81, 31);

        buttonreset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonreset.setText("RESET");
        buttonreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonresetActionPerformed(evt);
            }
        });
        jPanel2.add(buttonreset);
        buttonreset.setBounds(110, 640, 100, 31);

        buttonbook.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonbook.setText("BOOK");
        buttonbook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbookActionPerformed(evt);
            }
        });
        jPanel2.add(buttonbook);
        buttonbook.setBounds(850, 640, 90, 31);

        close.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText(" X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel2.add(close);
        close.setBounds(1050, 30, 40, 44);

        minimize.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        minimize.setForeground(new java.awt.Color(255, 255, 255));
        minimize.setText(" -");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        jPanel2.add(minimize);
        minimize.setBounds(1000, 30, 40, 44);

        tf_uangbyr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_uangbyrActionPerformed(evt);
            }
        });
        tf_uangbyr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_uangbyrKeyReleased(evt);
            }
        });
        jPanel2.add(tf_uangbyr);
        tf_uangbyr.setBounds(270, 530, 153, 26);

        tf_uangkembali.setEditable(false);
        tf_uangkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_uangkembaliActionPerformed(evt);
            }
        });
        jPanel2.add(tf_uangkembali);
        tf_uangkembali.setBounds(270, 570, 153, 26);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Uang Kembali         :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(70, 570, 169, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Uang Bayar            :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(70, 530, 169, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Harga Pokok           :");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(70, 450, 178, 22);

        tf_namafilm.setEditable(false);
        jPanel2.add(tf_namafilm);
        tf_namafilm.setBounds(270, 210, 150, 26);

        print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        print.setText("PRINT");
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel2.add(print);
        print.setBounds(960, 640, 100, 31);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasibookingtiketfix/24.jpg"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 1110, 700);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void checkbox_a1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_a1.getText();
        tf_nokursi.setText(kursi);
        checkbox_a1.setEnabled(false);
    }                                           

    private void checkbox_a2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_a2.getText();
        tf_nokursi.setText(kursi);
        checkbox_a2.setEnabled(false);
    }                                           

    private void checkbox_b1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_b1.getText();
        tf_nokursi.setText(kursi);
        checkbox_b1.setEnabled(false);
    }                                           

    private void checkbox_b2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_b2.getText();
        tf_nokursi.setText(kursi);
        checkbox_b2.setEnabled(false);
    }                                           

    private void checkbox_b3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_b3.getText();
        tf_nokursi.setText(kursi);
        checkbox_b3.setEnabled(false);
    }                                           

    private void checkbox_a3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_a3.getText();
        tf_nokursi.setText(kursi);
        checkbox_a3.setEnabled(false);
    }                                           

    private void checkbox_a4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_a4.getText();
        tf_nokursi.setText(kursi);
        checkbox_a4.setEnabled(false);
    }                                           

    private void checkbox_a5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_a5.getText();
        tf_nokursi.setText(kursi);
        checkbox_a5.setEnabled(false);
    }                                           

    private void checkbox_b4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_b4.getText();
        tf_nokursi.setText(kursi);
        checkbox_b4.setEnabled(false);
    }                                           

    private void checkbox_b5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_b5.getText();
        tf_nokursi.setText(kursi);
        checkbox_b5.setEnabled(false);
    }                                           

    private void checkbox_b6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_b6.getText();
        tf_nokursi.setText(kursi);
        checkbox_b6.setEnabled(false);
    }                                           

    private void checkbox_a6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        counter++;
        kursi = tf_nokursi.getText()+ checkbox_a6.getText();
        tf_nokursi.setText(kursi);
        checkbox_a6.setEnabled(false);
    }                                           

    private void konfirmasiActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if(String.valueOf(tf_hari.getText()).equals("Senin")){
            harga = 40000;
        }else if(String.valueOf(tf_hari.getText()).equals("Selasa")){
            harga = 40000;
        }else if(String.valueOf(tf_hari.getText()).equals("Rabu")){
            harga = 40000;
        }else if(String.valueOf(tf_hari.getText()).equals("Kamis")){
            harga = 40000;
        }else if(String.valueOf(tf_hari.getText()).equals("Jumat")){
            harga = 50000;
        }else if(String.valueOf(tf_hari.getText()).equals("Sabtu")){
            harga = 65000;
        }else if(String.valueOf(tf_hari.getText()).equals("Minggu")){
            harga = 65000;
        }
        hasil = counter * harga;
        tf_totalharga.setText(String.valueOf(hasil));
        tf_jmltiket.setText(String.valueOf(counter));
    }                                          

    private void buttonbackActionPerformed(java.awt.event.ActionEvent evt) {                                           
        MoviesForm mf = new MoviesForm();
        mf.setVisible(true);
        mf.pack();
        mf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }                                          

    private void buttonresetActionPerformed(java.awt.event.ActionEvent evt) {                                            
        tf_jmltiket.setText("");
        tf_totalharga.setText("");
        tf_uangbyr.setText("");
        tf_uangkembali.setText("");
        tf_nokursi.setText("");
        counter= 0;

        checkbox_a1.setEnabled(true);
        checkbox_a2.setEnabled(true);
        checkbox_a3.setEnabled(true);
        checkbox_a4.setEnabled(true);
        checkbox_a5.setEnabled(true);
        checkbox_a6.setEnabled(true);
        checkbox_b1.setEnabled(true);
        checkbox_b2.setEnabled(true);
        checkbox_b3.setEnabled(true);
        checkbox_b4.setEnabled(true);
        checkbox_b5.setEnabled(true);
        checkbox_b6.setEnabled(true);
        checkbox_a1.setSelected(false);
        checkbox_a2.setSelected(false);
        checkbox_a3.setSelected(false);
        checkbox_a4.setSelected(false);
        checkbox_a5.setSelected(false);
        checkbox_a6.setSelected(false);
        checkbox_b1.setSelected(false);
        checkbox_b2.setSelected(false);
        checkbox_b3.setSelected(false);
        checkbox_b4.setSelected(false);
        checkbox_b5.setSelected(false);
        checkbox_b6.setSelected(false);
    }                                           

    private void buttonbookActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String namafilm = tf_namafilm.getText();
        String hari = String.valueOf(tf_hari.getText());
        String tanggal = tf_tanggal.getText();
        String jamtayang= tf_jam.getText();
        String nokursi = tf_nokursi.getText();
        String jumlahtiket = tf_jmltiket.getText();
        String harga_total = tf_totalharga.getText();

        if(uang < hasil)
        {
            JOptionPane.showMessageDialog(null, "Booking Gagal! Pembayaran Anda Kurang Dari Nominal Yang Ditentukan!");
        }
        else if(validasikolom())
        {
            if(!validasikursi(namafilm, nokursi, tanggal, jamtayang))
            {
                PreparedStatement ps;
                ResultSet rs;
                String kursi_user_query = "INSERT INTO tb_booking (nama_film, tanggal, hari, jam, nomor_kursi, jumlah_tiket, total_harga) VALUES (?,?,?,?,?,?,?)" ;

                try {
                    // memanggil class javatomysql
                    ps = javatomysql.getConnection().prepareStatement(kursi_user_query);
                    // mengambil inputan
                    ps.setString(1, namafilm);
                    ps.setString(2, tanggal);
                    ps.setString(3, hari);
                    ps.setString(4, jamtayang);
                    ps.setString(5, nokursi);
                    ps.setString(6, jumlahtiket);
                    ps.setString(7, harga_total);

                    if(ps.executeUpdate()!=0){
                        // pesan sukses
                        JOptionPane.showMessageDialog(null, "Your Ticket Successfully Booked!");
                    }
                    else{
                        // pesan error
                        JOptionPane.showMessageDialog(null, "Error : Check Your Information");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(KursiStudioGK.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }                                          

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {                                   
        System.exit(0);
    }                                  

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {                                   
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        close.setBorder(judul_border);
        close.setForeground(Color.black);
    }                                  

    private void closeMouseExited(java.awt.event.MouseEvent evt) {                                  
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        close.setBorder(judul_border);
        close.setForeground(Color.white);
    }                                 

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {                                      
        this.setState(JFrame.ICONIFIED);
    }                                     

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {                                      
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        minimize.setBorder(judul_border);
        minimize.setForeground(Color.black);
    }                                     

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {                                     
        Border judul_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        minimize.setBorder(judul_border);
        minimize.setForeground(Color.white);
    }                                    

    private void tf_uangbyrActionPerformed(java.awt.event.ActionEvent evt) {                                           
        uang =Integer.parseInt(String.valueOf(tf_uangbyr.getText()));
        kembali = uang - hasil;
        tf_uangkembali.setText(String.valueOf(kembali));
    }                                          

    private void tf_uangbyrKeyReleased(java.awt.event.KeyEvent evt) {                                       
        uang =Integer.parseInt(String.valueOf(tf_uangbyr.getText()));
        kembali = uang - hasil;
        tf_uangkembali.setText(String.valueOf(kembali));
    }                                      

    private void tf_uangkembaliActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void printActionPerformed(java.awt.event.ActionEvent evt) {                                      
        DataTiket dt = new DataTiket();
        dt.setVisible(true);
        dt.pack();
        dt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }                                     
    public boolean validasikolom()
    {   // mengambil data
        String namafilm = tf_namafilm.getText();
        String hari = String.valueOf(tf_hari.getText());
        String jamtayang = tf_jam.getText();
        String nokursi = tf_nokursi.getText();
        String jumlahtiket = tf_jmltiket.getText();
        String harga_total = tf_totalharga.getText();
        
        // periksa kolom kosong
         if(namafilm.trim().equals("") || nokursi.trim().equals("") 
            || jumlahtiket.trim().equals("") || harga_total.trim().equals(""))
        { // jika kosong
           JOptionPane.showMessageDialog(null, "One Or More Field Are Empty","Empty Fields",2);
           return false;
        } // jika tidak kosong
        else{
            return true;
        }
    }

    public boolean validasikursi(String namafilm, String nokursi, String tanggal, String jamtayang){
        PreparedStatement st;
        ResultSet rs;
        boolean kursi_exist = false;

        String query = "SELECT * FROM tb_booking WHERE nama_film = ? and nomor_kursi like ? and tanggal = ? and jam = ?";

        try {
         // memanggil class javatomysql
            st = javatomysql.getConnection().prepareStatement(query);
            st.setString(1,namafilm);
            st.setString(2,"%"+nokursi+"%");
            st.setString(3,tanggal);
            st.setString(4,jamtayang);
            rs = st.executeQuery();           

            // jika akun sudah ada dalam database
            if(rs.next())
            {
                kursi_exist = true;
                // pesan error
                JOptionPane.showMessageDialog(null, "Kursi tidak tersedia");  
            }

        } catch (SQLException ex) {
            Logger.getLogger(KursiStudioGK.class.getName()).log(Level.SEVERE, null, ex);
        }
        return kursi_exist;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KursiStudioTB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KursiStudioTB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KursiStudioTB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KursiStudioTB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KursiStudioTB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonback;
    private javax.swing.JButton buttonbook;
    private javax.swing.JButton buttonreset;
    private javax.swing.JCheckBox checkbox_a1;
    private javax.swing.JCheckBox checkbox_a2;
    private javax.swing.JCheckBox checkbox_a3;
    private javax.swing.JCheckBox checkbox_a4;
    private javax.swing.JCheckBox checkbox_a5;
    private javax.swing.JCheckBox checkbox_a6;
    private javax.swing.JCheckBox checkbox_b1;
    private javax.swing.JCheckBox checkbox_b2;
    private javax.swing.JCheckBox checkbox_b3;
    private javax.swing.JCheckBox checkbox_b4;
    private javax.swing.JCheckBox checkbox_b5;
    private javax.swing.JCheckBox checkbox_b6;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton konfirmasi;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton print;
    public static javax.swing.JTextField tf_hargapokok;
    public static javax.swing.JTextField tf_hari;
    public static javax.swing.JTextField tf_jam;
    private javax.swing.JTextField tf_jmltiket;
    public static javax.swing.JTextField tf_namafilm;
    private javax.swing.JTextField tf_nokursi;
    public static javax.swing.JTextField tf_tanggal;
    public static javax.swing.JTextField tf_totalharga;
    private javax.swing.JTextField tf_uangbyr;
    private javax.swing.JTextField tf_uangkembali;
    // End of variables declaration                   
}
